application: refacoza
version: dev
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /blog/(\d+)
  script: main.app

- url: /static
  static_dir: static

- url: /.*
  script: main.app

libraries:                                                                      
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest
